name: Autograding Tests

on:
  push:
    branches:
      - main

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout submission
        uses: actions/checkout@v4

      - name: Grade based on submitted marks.txt
        id: grade_accuracy
        uses: github-classroom/echo-grader@v1
        with:
          test-command: |
            score=$(cat 6_deep_learning/CNN/tf_best_practices/binary_classification/marks.txt)
            echo "score=$score" >> $GITHUB_OUTPUT
          max-score: 100

      - name: Autograding Reporter
        uses: github-classroom/grading-reporter@v1
        env:
          GRADE_ACCURACY_RESULTS: "${{ steps.grade_accuracy.outputs.result }}"
        with:
          runners: grade_accuracy
