# This is a corrected and updated GitHub Actions workflow for autograding.
# It replaces the deprecated 'github-classroom/echo-grader' and 'github-classroom/grading-reporter'
# with the current, unified 'education/autograding@v1' action.
# This version dynamically creates the grading configuration based on a score in a file.

name: Autograding Tests

on:
  push:
    branches:
      - main

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    # This check prevents the workflow from running on commits made by the classroom bot itself.
    if: github.actor != 'github-classroom[bot]'
    steps:
      # Step 1: Check out the student's submission code from the repository.
      - name: Checkout submission
        uses: actions/checkout@v4

      # Step 2: Read the score from marks.txt and create the autograding JSON file.
      # The autograding action looks for this file by default.
      # We are dynamically setting the "points" value in the JSON based on the file content.
      - name: Create autograding config
        run: |
          mkdir -p .github/classroom
          score=$(cat 6_deep_learning/CNN/tf_best_practices/binary_classification/marks.txt)
          cat <<EOF > .github/classroom/autograding.json
          [
            {
              "name": "Grade based on submitted marks.txt",
              "setup": "",
              "run": "echo 'Awarding points based on file content.'",
              "input": "",
              "output": "",
              "comparison": "included",
              "points": ${score}
            }
          ]
          EOF

      # Step 3: Run the autograding action.
      # This action will now find and use the .github/classroom/autograding.json file
      # that was created in the previous step.
      - name: Autograding
        uses: education/autograding@v1
