# This is a corrected and updated GitHub Actions workflow for autograding.
# It replaces the deprecated 'github-classroom/echo-grader' and 'github-classroom/grading-reporter'
# with the current, unified 'education/autograding@v1' action.

name: Autograding Tests

on:
  push:
    branches:
      - main

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    # This check prevents the workflow from running on commits made by the classroom bot itself.
    if: github.actor != 'github-classroom[bot]'
    steps:
      # Step 1: Check out the student's submission code from the repository.
      - name: Checkout submission
        uses: actions/checkout@v4

      # Step 2: Run the autograding action.
      # This single action replaces the two older, deprecated actions.
      # It is configured to run a "test" that awards points based on the
      # score found in the 'marks.txt' file.
      - name: Autograding
        uses: education/autograding@v1
        with:
          # The 'tests' parameter defines the grading steps.
          # We create a single test here.
          tests: |
            [
              {
                "name": "Grade based on submitted marks.txt",
                "setup": "",
                "run": "cat 6_deep_learning/CNN/tf_best_practices/binary_classification/marks.txt",
                "input": "",
                "output": "",
                "comparison": "included",
                "points": 100,
                "timeout": 2
              }
            ]
